window.SEED_DATA = {
  "criteria": [
    {
      "id": "S01",
      "pillar": "Mandate & strategy",
      "capability": "Automation roadmap and prioritization",
      "question": "Can translate the 2026/27 mandate into a clear automation roadmap for a region or workstream.",
      "evidenceStandard": "Has created or owned a roadmap with clear priorities, dependencies, and decision gates.",
      "required": 5,
      "weight": 1.2,
      "gapType": "Skill"
    },
    {
      "id": "S02",
      "pillar": "Mandate & strategy",
      "capability": "Commercial and operational value framing",
      "question": "Can explain how automation supports cost, speed, capacity, quality, and customer retention.",
      "evidenceStandard": "Can frame automation value in business language for operations and commercial leadership.",
      "required": 5,
      "weight": 1.2,
      "gapType": "Skill"
    },
    {
      "id": "S03",
      "pillar": "Mandate & strategy",
      "capability": "Global blueprint / local execution model",
      "question": "Can define what must be standardized globally versus adapted locally.",
      "evidenceStandard": "Has created reusable standards while allowing local site adaptation.",
      "required": 5,
      "weight": 1.1,
      "gapType": "Skill"
    },
    {
      "id": "S04",
      "pillar": "Mandate & strategy",
      "capability": "Decision quality",
      "question": "Can make pragmatic trade-offs between ROI, complexity, integration risk, operational disruption, and scale potential.",
      "evidenceStandard": "Uses structured trade-off logic rather than vendor enthusiasm or isolated site preference.",
      "required": 4,
      "weight": 1,
      "gapType": "Skill"
    },
    {
      "id": "C01",
      "pillar": "Regional community enablement",
      "capability": "European A&I community leadership",
      "question": "Can build and manage an active European automation and innovation community across regions and sites.",
      "evidenceStandard": "Has built a network, created recurring engagement, and kept stakeholders contributing without heavy escalation.",
      "required": 5,
      "weight": 1.8,
      "gapType": "Geo/Capacity"
    },
    {
      "id": "C02",
      "pillar": "Regional community enablement",
      "capability": "Proactive pain-point collection",
      "question": "Can get sites to share operational issues, active initiatives, constraints, and improvement ideas.",
      "evidenceStandard": "Can convert weak or unstructured site input into a usable pipeline of automation opportunities.",
      "required": 5,
      "weight": 1.7,
      "gapType": "Skill"
    },
    {
      "id": "C03",
      "pillar": "Regional community enablement",
      "capability": "Influence without authority",
      "question": "Can motivate regional/site teams to do additional work because the benefit is clear to them.",
      "evidenceStandard": "Can secure participation without relying on hierarchy or repeated escalation.",
      "required": 5,
      "weight": 1.8,
      "gapType": "Behavior"
    },
    {
      "id": "C04",
      "pillar": "Regional community enablement",
      "capability": "Stakeholder storytelling",
      "question": "Can explain the community value proposition clearly to operations, engineering, commercial, and senior leaders.",
      "evidenceStandard": "Can make the work feel useful to regions, not like a global reporting burden.",
      "required": 5,
      "weight": 1.5,
      "gapType": "Behavior"
    },
    {
      "id": "C05",
      "pillar": "Regional community enablement",
      "capability": "Follow-through and cadence management",
      "question": "Can run forums, collect actions, track owners, close loops, and maintain momentum.",
      "evidenceStandard": "Has managed multi-stakeholder cadence with visible outputs and accountability.",
      "required": 4,
      "weight": 1.3,
      "gapType": "Behavior"
    },
    {
      "id": "C06",
      "pillar": "Regional community enablement",
      "capability": "Travel and site engagement readiness",
      "question": "Can spend meaningful time on site and build trust with operations across Europe.",
      "evidenceStandard": "Comfortable with frequent site visits, workshops, and direct operational engagement.",
      "required": 4,
      "weight": 1.2,
      "gapType": "Capacity"
    },
    {
      "id": "A01",
      "pillar": "Automation solutioning",
      "capability": "Brownfield retrofit assessment",
      "question": "Can identify practical mechanization/automation options to increase capacity in existing buildings.",
      "evidenceStandard": "Can assess conveyors, sorters, storage, AMRs, MHE, and process changes in constrained operations.",
      "required": 5,
      "weight": 1.5,
      "gapType": "Skill"
    },
    {
      "id": "A02",
      "pillar": "Automation solutioning",
      "capability": "RFQ / new business automation input",
      "question": "Can support strategic RFQs/new launches with the right level of automation input when required.",
      "evidenceStandard": "Can prevent poor pricing, overdesign, missed automation scope, or unrealistic vendor assumptions.",
      "required": 4,
      "weight": 1.2,
      "gapType": "Skill"
    },
    {
      "id": "A03",
      "pillar": "Automation solutioning",
      "capability": "Solution concept design",
      "question": "Can develop concept options with layouts, process logic, throughput assumptions, and boundary conditions.",
      "evidenceStandard": "Has created credible concepts before vendor RFQ stage.",
      "required": 5,
      "weight": 1.5,
      "gapType": "Skill"
    },
    {
      "id": "A04",
      "pillar": "Automation solutioning",
      "capability": "Technology fit assessment",
      "question": "Can match automation technology to process profile, volume, SKU mix, labor model, and site constraints.",
      "evidenceStandard": "Can explain why a solution fits or does not fit a specific warehouse profile.",
      "required": 5,
      "weight": 1.4,
      "gapType": "Skill"
    },
    {
      "id": "A05",
      "pillar": "Automation solutioning",
      "capability": "Vendor solution challenge",
      "question": "Can challenge vendor concepts, assumptions, costs, layouts, and performance claims.",
      "evidenceStandard": "Can identify gaps in vendor proposals and push for better designs or pricing.",
      "required": 5,
      "weight": 1.3,
      "gapType": "Skill"
    },
    {
      "id": "A06",
      "pillar": "Automation solutioning",
      "capability": "Standard solution definition",
      "question": "Can define repeatable standard solution patterns based on evidence from past RFQs and site needs.",
      "evidenceStandard": "Can turn recurring demand patterns into approved reference designs.",
      "required": 5,
      "weight": 1.5,
      "gapType": "Skill"
    },
    {
      "id": "L01",
      "pillar": "Automation library / catalogue",
      "capability": "Catalogue content ownership",
      "question": "Can build and maintain structured content for approved vendors, technologies, design templates, and use cases.",
      "evidenceStandard": "Has created knowledge assets that others can reuse without asking the original expert.",
      "required": 5,
      "weight": 1.6,
      "gapType": "Skill"
    },
    {
      "id": "L02",
      "pillar": "Automation library / catalogue",
      "capability": "Reference architecture thinking",
      "question": "Can document standard layouts, flow concepts, decision trees, and boundary conditions.",
      "evidenceStandard": "Can make the library actionable, not just a list of vendors.",
      "required": 5,
      "weight": 1.5,
      "gapType": "Skill"
    },
    {
      "id": "L03",
      "pillar": "Automation library / catalogue",
      "capability": "Knowledge capture discipline",
      "question": "Can convert RFQ work, vendor assessments, PoC learnings, and regional projects into reusable assets.",
      "evidenceStandard": "Evidence is captured within 30 days and structured for reuse.",
      "required": 4,
      "weight": 1.3,
      "gapType": "Behavior"
    },
    {
      "id": "L04",
      "pillar": "Automation library / catalogue",
      "capability": "User adoption",
      "question": "Can drive adoption of the product catalogue across regions and reduce reinventing the wheel.",
      "evidenceStandard": "Can get people to use the library and provide feedback.",
      "required": 5,
      "weight": 1.4,
      "gapType": "Behavior"
    },
    {
      "id": "L05",
      "pillar": "Automation library / catalogue",
      "capability": "Governance of standards",
      "question": "Can keep standards current, retire weak solutions, and maintain quality control over catalogue content.",
      "evidenceStandard": "Can operate a controlled library with owners, review dates, and version discipline.",
      "required": 4,
      "weight": 1.2,
      "gapType": "Skill"
    },
    {
      "id": "V01",
      "pillar": "Vendor and SRM",
      "capability": "Vendor landscape understanding",
      "question": "Can compare major vendors and emerging suppliers across core automation categories.",
      "evidenceStandard": "Understands strengths, weaknesses, pricing logic, maturity, and regional support model.",
      "required": 4,
      "weight": 1.1,
      "gapType": "Skill"
    },
    {
      "id": "V02",
      "pillar": "Vendor and SRM",
      "capability": "Structured vendor assessment",
      "question": "Can assess vendors using consistent criteria: capability, cost, support, integration, safety, references, and scale readiness.",
      "evidenceStandard": "Uses a repeatable scorecard rather than informal preference.",
      "required": 5,
      "weight": 1.3,
      "gapType": "Skill"
    },
    {
      "id": "V03",
      "pillar": "Vendor and SRM",
      "capability": "Commercial leverage support",
      "question": "Can support SRM with evidence that improves pricing, terms, service levels, or framework agreements.",
      "evidenceStandard": "Can translate technical demand into better commercial leverage.",
      "required": 4,
      "weight": 1.1,
      "gapType": "Skill"
    },
    {
      "id": "V04",
      "pillar": "Vendor and SRM",
      "capability": "Vendor playbooks",
      "question": "Can create vendor playbooks including scope fit, commercials, risks, implementation model, and support expectations.",
      "evidenceStandard": "Regions can use the playbook without restarting vendor due diligence.",
      "required": 4,
      "weight": 1.1,
      "gapType": "Skill"
    },
    {
      "id": "P01",
      "pillar": "PoC and R&D",
      "capability": "PoC design",
      "question": "Can define a controlled PoC with hypothesis, scope, baseline, target KPIs, risks, and exit criteria.",
      "evidenceStandard": "Has designed a PoC that produces clear go/no-go evidence.",
      "required": 5,
      "weight": 1.3,
      "gapType": "Skill"
    },
    {
      "id": "P02",
      "pillar": "PoC and R&D",
      "capability": "Emerging hardware assessment",
      "question": "Can assess robotics, AMRs, inventory robots, machine vision, smart sensors, scanners, and low-cost MHE concepts.",
      "evidenceStandard": "Can separate useful emerging tech from vendor hype.",
      "required": 5,
      "weight": 1.3,
      "gapType": "Skill"
    },
    {
      "id": "P03",
      "pillar": "PoC and R&D",
      "capability": "Prototype thinking",
      "question": "Can help shape practical prototypes for customer or site problems without overengineering.",
      "evidenceStandard": "Can move from problem to minimum testable setup.",
      "required": 4,
      "weight": 1,
      "gapType": "Skill"
    },
    {
      "id": "P04",
      "pillar": "PoC and R&D",
      "capability": "Scale decision after PoC",
      "question": "Can translate PoC results into scale prerequisites, limitations, cost drivers, and next steps.",
      "evidenceStandard": "The output is a playbook or decision pack, not just a pilot report.",
      "required": 5,
      "weight": 1.3,
      "gapType": "Skill"
    },
    {
      "id": "P05",
      "pillar": "PoC and R&D",
      "capability": "Balanced innovation judgment",
      "question": "Can keep R&D focused on operational value and future-proofing, not novelty.",
      "evidenceStandard": "Prioritizes business outcome over technology excitement.",
      "required": 5,
      "weight": 1,
      "gapType": "Behavior"
    },
    {
      "id": "I01",
      "pillar": "Integration readiness",
      "capability": "Integration blueprint definition",
      "question": "Can define the integration questions needed before scale: WMS/WES/ERP, data flows, security, alerts, ownership, support.",
      "evidenceStandard": "Can create a practical integration blueprint for scaling.",
      "required": 5,
      "weight": 1.4,
      "gapType": "Skill"
    },
    {
      "id": "I02",
      "pillar": "Integration readiness",
      "capability": "IT/OT collaboration",
      "question": "Can work with digital, IT, security, operations, and vendors to clarify integration responsibilities.",
      "evidenceStandard": "Can prevent scale blockers caused by late IT/OT involvement.",
      "required": 4,
      "weight": 1.1,
      "gapType": "Behavior"
    },
    {
      "id": "I03",
      "pillar": "Integration readiness",
      "capability": "Physical AI interface understanding",
      "question": "Can identify where computer vision, sensors, scanners, and physical AI improve existing hardware.",
      "evidenceStandard": "Understands hardware/process/data interface enough to guide useful discussions.",
      "required": 4,
      "weight": 1.1,
      "gapType": "Skill"
    },
    {
      "id": "I04",
      "pillar": "Integration readiness",
      "capability": "Operational support model",
      "question": "Can define support, maintenance, exception handling, and ownership model for scaled solutions.",
      "evidenceStandard": "Can move beyond PoC demo to run-and-maintain logic.",
      "required": 4,
      "weight": 1.1,
      "gapType": "Skill"
    },
    {
      "id": "D01",
      "pillar": "Data, ROI and evidence",
      "capability": "Operational data interpretation",
      "question": "Can interpret warehouse data, process maps, volume profiles, labor assumptions, and performance baselines.",
      "evidenceStandard": "Can identify automation potential from operational evidence.",
      "required": 5,
      "weight": 1.4,
      "gapType": "Skill"
    },
    {
      "id": "D02",
      "pillar": "Data, ROI and evidence",
      "capability": "Pain-point library structuring",
      "question": "Can organize site pain points by process, vertical, value lever, technology fit, and priority.",
      "evidenceStandard": "Can turn scattered regional input into a managed opportunity library.",
      "required": 5,
      "weight": 1.4,
      "gapType": "Skill"
    },
    {
      "id": "D03",
      "pillar": "Data, ROI and evidence",
      "capability": "ROI and TCO modelling",
      "question": "Can build or review practical ROI/TCO logic for automation options.",
      "evidenceStandard": "Can quantify labor, space, throughput, quality, maintenance, risk, and payback.",
      "required": 5,
      "weight": 1.3,
      "gapType": "Skill"
    },
    {
      "id": "D04",
      "pillar": "Data, ROI and evidence",
      "capability": "Benefit tracking",
      "question": "Can define how benefits will be measured after PoC or deployment.",
      "evidenceStandard": "Can avoid vague success claims by using baselines and comparable measurement windows.",
      "required": 4,
      "weight": 1,
      "gapType": "Skill"
    },
    {
      "id": "D05",
      "pillar": "Data, ROI and evidence",
      "capability": "Evidence-based standardization",
      "question": "Can use historical RFQs, customer demands, site issues, and project results to define standard solutions.",
      "evidenceStandard": "Standards are based on evidence, not personal preference.",
      "required": 5,
      "weight": 1.2,
      "gapType": "Skill"
    },
    {
      "id": "G01",
      "pillar": "Geographic coverage and capacity",
      "capability": "Europe demand coverage",
      "question": "Has enough capacity and proximity to support European sites, workshops, travel, and community cadence.",
      "evidenceStandard": "Can cover Europe without pushing all coordination back to the global lead.",
      "required": 5,
      "weight": 2,
      "gapType": "Geo/Capacity"
    },
    {
      "id": "G02",
      "pillar": "Geographic coverage and capacity",
      "capability": "APAC/Oceania demand coverage",
      "question": "Has enough realistic demand and workload to justify a dedicated APAC/Oceania focus.",
      "evidenceStandard": "Can show active pipeline, community pull, and regional value.",
      "required": 3,
      "weight": 0.8,
      "gapType": "Geo/Capacity"
    },
    {
      "id": "G03",
      "pillar": "Geographic coverage and capacity",
      "capability": "Americas coordination",
      "question": "Can coordinate with the Americas team and transfer standards without duplicating work.",
      "evidenceStandard": "Can align outputs across regions while keeping ownership clear.",
      "required": 3,
      "weight": 0.8,
      "gapType": "Geo/Capacity"
    },
    {
      "id": "G04",
      "pillar": "Geographic coverage and capacity",
      "capability": "Available bandwidth",
      "question": "Has sufficient available time to lead community, library, PoC, and regional enablement work.",
      "evidenceStandard": "Can absorb work without constant reprioritization or task-by-task feeding.",
      "required": 5,
      "weight": 1.8,
      "gapType": "Capacity"
    },
    {
      "id": "G05",
      "pillar": "Geographic coverage and capacity",
      "capability": "Proactive ownership",
      "question": "Can identify work, frame the problem, propose options, and move forward without needing detailed task feeding.",
      "evidenceStandard": "Brings problems and solutions, not only completed assigned tasks.",
      "required": 5,
      "weight": 1.8,
      "gapType": "Behavior"
    }
  ],
  "participants": [
    {
      "id": "lawrence",
      "name": "Lawrence",
      "selfScores": {
        "S01": 4,
        "S02": 4,
        "S03": 3,
        "S04": 3,
        "C01": 3,
        "C02": 3,
        "C03": 3,
        "C04": 3,
        "C05": 3,
        "C06": 3,
        "A01": 4,
        "A02": 4,
        "A03": 4,
        "A04": 4,
        "A05": 4,
        "A06": 4,
        "L01": 4,
        "L02": 4,
        "L03": 4,
        "L04": 4,
        "L05": 4,
        "V01": 4,
        "V02": 4,
        "V03": 3,
        "V04": 3,
        "P01": 4,
        "P02": 4,
        "P03": 4,
        "P04": 3,
        "P05": 3,
        "I01": 3,
        "I02": 3,
        "I03": 3,
        "I04": 2,
        "D01": 4,
        "D02": 4,
        "D03": 3,
        "D04": 3,
        "D05": 4,
        "G01": 3,
        "G02": 4,
        "G03": 1,
        "G04": 2,
        "G05": 3
      },
      "managerScores": {
        "S01": 4,
        "S02": 4,
        "S03": 3,
        "S04": 3,
        "C01": 3,
        "C02": 3,
        "C03": 3,
        "C04": 3,
        "C05": 3,
        "C06": 3,
        "A01": 4,
        "A02": 4,
        "A03": 4,
        "A04": 4,
        "A05": 4,
        "A06": 4,
        "L01": 4,
        "L02": 4,
        "L03": 4,
        "L04": 4,
        "L05": 4,
        "V01": 4,
        "V02": 4,
        "V03": 3,
        "V04": 3,
        "P01": 4,
        "P02": 4,
        "P03": 4,
        "P04": 3,
        "P05": 3,
        "I01": 3,
        "I02": 3,
        "I03": 3,
        "I04": 2,
        "D01": 4,
        "D02": 4,
        "D03": 3,
        "D04": 3,
        "D05": 4,
        "G01": 3,
        "G02": 4,
        "G03": 1,
        "G04": 2,
        "G05": 3
      },
      "evidence": {
        "S01": "Automation roadmap was completed"
      },
      "sourceFiles": [
        "Lawrence_DPW_Automation_Innovation_Skills_Gap_Analysis_Individual_Template (002).xlsx"
      ]
    },
    {
      "id": "diego",
      "name": "Diego",
      "selfScores": {
        "S01": 4,
        "S02": 5,
        "S03": 5,
        "S04": 5,
        "C01": 4,
        "C02": 4,
        "C03": 4,
        "C04": 5,
        "C05": 3,
        "C06": 5,
        "A01": 5,
        "A02": 4,
        "A03": 4,
        "A04": 5,
        "A05": 4,
        "A06": 5,
        "L01": 4,
        "L02": 5,
        "L03": 5,
        "L04": 3,
        "L05": 4,
        "V01": 4,
        "V02": 4,
        "V03": 5,
        "V04": 4,
        "P01": 4,
        "P02": 5,
        "P03": 5,
        "P04": 5,
        "P05": 5,
        "I01": 5,
        "I02": 2,
        "I03": 3,
        "I04": 4,
        "D01": 5,
        "D02": 5,
        "D03": 5,
        "D04": 5,
        "D05": 5,
        "G01": 4,
        "G02": 2,
        "G03": 5,
        "G04": 3,
        "G05": 5
      },
      "managerScores": {
        "S01": 4,
        "S02": 5,
        "S03": 5,
        "S04": 5,
        "C01": 4,
        "C02": 4,
        "C03": 4,
        "C04": 5,
        "C05": 3,
        "C06": 5,
        "A01": 5,
        "A02": 4,
        "A03": 4,
        "A04": 5,
        "A05": 4,
        "A06": 5,
        "L01": 4,
        "L02": 5,
        "L03": 5,
        "L04": 3,
        "L05": 4,
        "V01": 4,
        "V02": 4,
        "V03": 5,
        "V04": 4,
        "P01": 4,
        "P02": 5,
        "P03": 5,
        "P04": 5,
        "P05": 5,
        "I01": 5,
        "I02": 2,
        "I03": 3,
        "I04": 4,
        "D01": 5,
        "D02": 5,
        "D03": 5,
        "D04": 5,
        "D05": 5,
        "G01": 4,
        "G02": 2,
        "G03": 5,
        "G04": 3,
        "G05": 5
      },
      "evidence": {
        "S01": "Humanoid project",
        "S02": "-AMR Solution BMW.\n-Robotic arm Solution BMW.\n-AMR Solution Speyer.",
        "S03": "-not yet within DPW",
        "S04": "-AMR Solution BMW.\n-Robotic arm Solution BMW.\n-AMR Solution Speyer.\n-Computer Vision Perris.",
        "C01": "-Slowly getting there. I started to visit more sites to gain visibility and bring more exposure to our team regionally. I am still to visit more site outsite NL and GER. ",
        "C02": "-VW/Leipzig/Venray/Zary/Wolfenbüttel/Kabelsketal/EU Solutions Eng/ have reached out to me directly to work and support specific automation initiatives including AMRs/Inventory/Simulation/Humanoids. I have been seeing as the main point of contact when it comes to Innovation innitiaves. ",
        "C03": "-Every team is different. Two good examples: Speyer is highly motivated and engaged and will support fully. On the other hand, Halberstadt has not provided the same level of support and commitment, therefore I had to take the lead in some of the tasks that were initially assigned to the local team. The same sitation I see now with Humanoids in U.S. While Carlisle is very exhited and cooperative, I have struggled to get the same response from York, failing to provide basic information which after long time digging I was able to find the SME of the process and get him on-board. ",
        "C05": "-not yet fully in a e2e project.",
        "C06": "-Visited 20+ sites over the first year. All of them still reach out for help. ",
        "A01": "-This is my field of expertise and where I have brought the most value across my career. I have a good understanding of warehouse process in a very detail level, as well as understanding of the current and emerging technologies capabilities.",
        "A02": "-Dell Brazil renewal. Perhaps the scope was missing from the beginning but the automated solution proposed met the requirements from operations",
        "A03": "-Dell Brazil",
        "A05": "- up to certain extend and depends on the solution proposed. ",
        "L04": "-This is more a teamwork rather than individual work. I see no standards in DPW. We are developing internally, other teams are more mature, many others are not. We have to be adaptable",
        "L05": "Humanoid project",
        "V01": "-Dell Brazil",
        "V02": "-Dell Brazil",
        "V03": "-AMR Solution BMW.\n-Robotic arm Solution BMW.\n-AMR Solution Speyer.",
        "P01": "-Computer Vision project with Roboflow.\n-Currently with humanoids project",
        "P04": "-Currently creating one for Dexory, and Humanoid technology",
        "P05": "-Humanoid project. I have spent most of my time educating people internally on what the technology can deliver today. Contuniously reaching out to vendors, attending events, taking courses, and constanlty being informed aboutt he development of the technology. ",
        "I03": "-Up to certain extend.",
        "D01": "-I believe the automation workshops were a good idea. This is the best way to apply this point. Even if at the end we don't enforce the automation, it creates visibility and a sense of collaboration between the sites and the global team. This should continue in the same structure way.",
        "G01": "-attached to familiy situation which will improve in 1+ year",
        "G03": "-Working activitely together with Raffael to identify and support initiatives with Dexory and Humanoid technologies in AMR",
        "G04": "- I would like to keep focus on identification of operational, escalable solutions and creating the playbooks for them. My strenght comes from having deep knowledge of the operations and relatively good understanding of the cutting edge technologies, where I can interact as a bridge to bring those innovations over to operations. "
      },
      "sourceFiles": [
        "Diego_Team Gap Analysis Self Assessment Diego Delgado.xlsx"
      ]
    },
    {
      "id": "raffael",
      "name": "Raffael",
      "selfScores": {},
      "managerScores": {},
      "evidence": {},
      "sourceFiles": [
        "DPW_Automation_Innovation_Skills_Gap_Analysis_Template.xlsx"
      ]
    },
    {
      "id": "manager-notes",
      "name": "Manager notes",
      "selfScores": {},
      "managerScores": {},
      "evidence": {},
      "sourceFiles": [
        "DPW_Automation_Innovation_Skills_Gap_Analysis_Template.xlsx"
      ]
    }
  ]
};
